version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: news-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: news_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8
    container_name: news-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  news-api:
    build: .
    container_name: news-api
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  postgres_data:
  redis_data:
